from __future__ import annotations

from pathlib import Path

from api.main import application as app
from scripts.generate_api_types import TARGET, generate


def response_schema(path: str, method: str = "get") -> dict:
    return app.openapi()["paths"][path][method]["responses"]["200"]["content"]["application/json"]["schema"]


def test_preview_response_is_a_named_full_contract() -> None:
    assert response_schema("/api/preview-design") == {"$ref": "#/components/schemas/PreviewDesign"}
    schemas = app.openapi()["components"]["schemas"]
    assert schemas["PreviewDesign"]["properties"]["product"] == {"$ref": "#/components/schemas/Product"}
    assert schemas["PreviewDesign"]["properties"]["room"] == {"$ref": "#/components/schemas/RoomShell"}


def test_validation_response_is_a_discriminated_fit_contract() -> None:
    assert response_schema("/api/placement-validation", "post") == {"$ref": "#/components/schemas/FitResult"}
    schema = app.openapi()["components"]["schemas"]["FitResult"]
    assert schema["discriminator"]["propertyName"] == "status"
    assert len(schema["oneOf"]) == 2


def test_success_responses_are_not_generic_objects() -> None:
    for path, method in (("/api/health", "get"), ("/api/preview-design", "get"), ("/api/placement-validation", "post")):
        schema = response_schema(path, method)
        assert schema.get("additionalProperties") is not True
        assert "$ref" in schema


def test_frontend_types_are_generated_from_current_openapi() -> None:
    assert TARGET.read_text(encoding="utf-8") == generate()
    assert "Generated by scripts/generate_api_types.py from FastAPI OpenAPI" in TARGET.read_text(encoding="utf-8")


def test_generated_contract_has_frontend_entry_types() -> None:
    text = Path(TARGET).read_text(encoding="utf-8")
    for declaration in ("interface PreviewDesign", "interface Product", "interface RoomShell", "type FitResult"):
        assert declaration in text
