import { useMemo } from 'react';
import { DoubleSide, FrontSide, Shape } from 'three';
import type { RoomShell } from '@/shared/api/types';
export function RoomShellMesh({ room, contactWallId }: { room: RoomShell; contactWallId: string | null }) {
  const centre = useMemo(() => room.floorPolygon.reduce<[number, number]>((sum, point) => [sum[0] + point[0], sum[1] + point[1]], [0, 0]).map((value) => value / room.floorPolygon.length) as [number, number], [room]);
  const walls = useMemo(() => room.walls.map((wall) => { const normal = wallInwardNormal(wall, centre); return { id: wall.id, lengthM: Math.hypot(wall.end[0] - wall.start[0], wall.end[1] - wall.start[1]), yaw: Math.atan2(normal[0], normal[1]), midpoint: [(wall.start[0] + wall.end[0]) / 2, (wall.start[1] + wall.end[1]) / 2] as const }; }), [room, centre]);
  const floor = useMemo(() => { const shape = new Shape(); const [first, ...rest] = room.floorPolygon; shape.moveTo(first![0], first![1]); for (const point of rest) shape.lineTo(point[0], point[1]); shape.closePath(); return shape; }, [room]);
  const gridSize = useMemo(() => { const xs = room.floorPolygon.map((point) => point[0]); const zs = room.floorPolygon.map((point) => point[1]); return Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...zs) - Math.min(...zs)); }, [room]);
  return <group name="room-shell"><mesh rotation={[Math.PI / 2, 0, 0]} position={[0, 0, 0]} receiveShadow><shapeGeometry args={[floor]} /><meshStandardMaterial color="#cfc8bd" roughness={0.95} metalness={0} side={DoubleSide} /></mesh>{walls.map((wall) => <mesh key={wall.id} name={wall.id} position={[wall.midpoint[0], room.ceilingHeightM / 2, wall.midpoint[1]]} rotation={[0, wall.yaw, 0]} receiveShadow><planeGeometry args={[wall.lengthM, room.ceilingHeightM]} /><meshStandardMaterial color={wall.id === contactWallId ? '#e8e2d6' : '#f2efe9'} roughness={1} metalness={0} side={FrontSide} /></mesh>)}<gridHelper args={[gridSize, Math.max(1, Math.round(gridSize)), '#b3aa9c', '#c6bfb2']} position={[centre[0], 0.002, centre[1]]} />{walls.map((wall) => <mesh key={`${wall.id}-skirting`} position={[wall.midpoint[0], 0.04, wall.midpoint[1]]} rotation={[0, wall.yaw, 0]}><planeGeometry args={[wall.lengthM, 0.08]} /><meshStandardMaterial color="#e2dcd0" roughness={1} side={DoubleSide} /></mesh>)}</group>;
}
function wallInwardNormal(wall: RoomShell['walls'][number], centre: readonly [number, number]): readonly [number, number] { const dx = wall.end[0] - wall.start[0]; const dz = wall.end[1] - wall.start[1]; const length = Math.hypot(dx, dz); const candidate = [-dz / length, dx / length] as const; const midpoint = [(wall.start[0] + wall.end[0]) / 2, (wall.start[1] + wall.end[1]) / 2] as const; return candidate[0] * (centre[0] - midpoint[0]) + candidate[1] * (centre[1] - midpoint[1]) >= 0 ? candidate : [-candidate[0], -candidate[1]]; }
