"""Generate the browser contract from FastAPI's OpenAPI component schemas."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from api.main import create_app  # noqa: E402 - ROOT must be importable first.

# Generate the complete typed contract, including the explicitly gated
# measurement endpoint. Runtime registration remains disabled by default.
app = create_app(enable_catalogue_gallery=True)

TARGET = ROOT / "src" / "shared" / "api" / "types.ts"


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for union_key in ("oneOf", "anyOf"):
        if union_key in schema:
            return " | ".join(ts_type(member) for member in schema[union_key])
    kind = schema.get("type")
    if kind == "array":
        if "prefixItems" in schema:
            return "readonly [" + ", ".join(ts_type(item) for item in schema["prefixItems"]) + "]"
        return f"ReadonlyArray<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        required = set(schema.get("required", []))
        fields = " ".join(
            f"readonly {name}{'' if name in required else '?'}: {ts_type(value)};"
            for name, value in schema.get("properties", {}).items()
        )
        return "{ " + fields + " }"
    return {"string": "string", "number": "number", "integer": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generate() -> str:
    schemas = app.openapi()["components"]["schemas"]
    lines = [
        "// Generated by scripts/generate_api_types.py from FastAPI OpenAPI. Do not edit.",
        "",
        "export type Vec2 = WallSegment['start'];",
        "export type Vec3 = Placement['position'];",
        "export type ProductFace = AccessRegion['face'];",
        "",
    ]
    for name in sorted(schemas):
        if name in {"HTTPValidationError", "ValidationError"}:
            continue
        schema = schemas[name]
        if schema.get("type") == "object":
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for field, value in schema.get("properties", {}).items():
                optional = "" if field in required else "?"
                lines.append(f"  readonly {field}{optional}: {ts_type(value)};")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != generated:
            print(f"{TARGET.relative_to(ROOT)} is stale; run uv run python scripts/generate_api_types.py")
            return 1
        return 0
    TARGET.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
