// Generated by scripts/generate_api_types.py from FastAPI OpenAPI. Do not edit.

export type Vec2 = WallSegment['start'];
export type Vec3 = Placement['position'];
export type ProductFace = AccessRegion['face'];

export interface AccessRegion {
  readonly face: "front" | "back" | "left" | "right";
  readonly depthM: number;
  readonly required: boolean;
  readonly purpose: string;
}

export interface Attribution {
  readonly source: string;
  readonly holder: string;
  readonly license: string;
  readonly licenseUrl: string;
  readonly sourceUrl: string;
  readonly materialUrl: string;
  readonly citation: string;
  readonly modifications: string;
  readonly licenseStatus: "verified" | "unknown" | "conflicting-source-records";
  readonly licenseNote: string;
  readonly licenseEvidence: ReadonlyArray<LicenseEvidence>;
}

export interface CatalogueGallery {
  readonly catalogueVersion: string;
  readonly products: ReadonlyArray<Product>;
}

export interface Dimensions {
  readonly widthM: number;
  readonly heightM: number;
  readonly depthM: number;
}

export interface FitMeasurements {
  readonly footprint: Footprint;
  readonly clearanceM: number;
  readonly wallGapM: number | null;
  readonly heightM: number;
  readonly floorGapM: number;
  readonly topM: number;
}

export type FitResult = FitSuccess | InvalidFit;

export interface FitSuccess {
  readonly status: "fits";
  readonly placement: Placement;
  readonly measurements: FitMeasurements;
}

export interface Footprint {
  readonly centre: readonly [number, number];
  readonly yaw: number;
  readonly widthM: number;
  readonly depthM: number;
  readonly corners: readonly [readonly [number, number], readonly [number, number], readonly [number, number], readonly [number, number]];
}

export interface Health {
  readonly status: "ok";
}

export interface InvalidFit {
  readonly status: "invalid-fit";
  readonly reason: "product-exceeds-room-bounds" | "footprint-outside-room" | "access-region-outside-room" | "wall-contact-face-not-allowed" | "not-touching-declared-wall" | "wall-shorter-than-product" | "exceeds-ceiling-height" | "placement-class-cannot-stand-on-floor" | "not-resting-on-floor";
  readonly detail: string;
  readonly productId: string;
  readonly roomId: string;
  readonly measurements: FitMeasurements;
}

export interface LicenseEvidence {
  readonly label: string;
  readonly recordedLicense: string;
  readonly url: string;
}

export interface MeshBounds {
  readonly min: readonly [number, number, number];
  readonly max: readonly [number, number, number];
}

export interface MeshLod {
  readonly level: 0 | 1 | 2;
  readonly url: string;
  readonly triangles: number;
  readonly exclusiveBytes: number;
}

export interface MeshNormalization {
  readonly unit: "m";
  readonly upAxis: "+y";
  readonly frontAxis: "+z";
  readonly originRule: "floor-centre";
  readonly transform: MeshTransform;
  readonly note: string;
}

export interface MeshRef {
  readonly lods: ReadonlyArray<MeshLod>;
  readonly sharedTextureUrls: ReadonlyArray<string>;
  readonly normalization: MeshNormalization;
  readonly boundsM: MeshBounds;
  readonly totalCompressedBytes: number;
}

export interface MeshTransform {
  readonly translation: readonly [number, number, number];
  readonly rotationYaw: number;
  readonly scale: number;
}

export interface Placement {
  readonly productId: string;
  readonly position: readonly [number, number, number];
  readonly yaw: number;
  readonly wallContact?: WallContact | null;
}

export interface PlacementValidationRequest {
  readonly product: Product;
  readonly room: RoomShell;
  readonly placement: Placement;
}

export interface PreviewDesign {
  readonly room: RoomShell;
  readonly product: Product;
  readonly fit: FitSuccess | InvalidFit;
}

export interface Product {
  readonly id: string;
  readonly displayName: string;
  readonly brand: string;
  readonly colour: string;
  readonly category: "bed" | "nightstand" | "wardrobe" | "dresser" | "chair" | "sofa" | "table" | "rug" | "lamp";
  readonly roomTypes: ReadonlyArray<"bedroom" | "living-room">;
  readonly dimensionsM: Dimensions;
  readonly frontAxis: "+z";
  readonly wallContactFaces: ReadonlyArray<"front" | "back" | "left" | "right">;
  readonly placementClass: "floor-standing" | "wall-mounted" | "ceiling-hung" | "surface-standing";
  readonly accessRegions: ReadonlyArray<AccessRegion>;
  readonly mesh: MeshRef;
  readonly purchaseUrl: string;
  readonly purchase: PurchaseDisclosure;
  readonly attribution: Attribution;
}

export interface PurchaseDisclosure {
  readonly availability: "purchasable" | "unavailable" | "unknown";
  readonly checkedOn: string;
  readonly note: string;
}

export interface RoomShell {
  readonly id: string;
  readonly floorPolygon: ReadonlyArray<readonly [number, number]>;
  readonly walls: ReadonlyArray<WallSegment>;
  readonly ceilingHeightM: number;
}

export interface WallContact {
  readonly wallId: string;
  readonly face: "front" | "back" | "left" | "right";
}

export interface WallSegment {
  readonly id: string;
  readonly label: string;
  readonly start: readonly [number, number];
  readonly end: readonly [number, number];
}
