// Generated by scripts/generate_api_types.py from FastAPI OpenAPI. Do not edit.

export type Vec2 = WallSegment['start'];
export type Vec3 = Placement['position'];
export type ProductFace = AccessRegion['face'];

export interface AccessRegion {
  readonly face: "front" | "back" | "left" | "right";
  readonly depthM: number;
  readonly required: boolean;
  readonly purpose: string;
}

export interface ArrangementAttempt {
  readonly id: string;
  readonly stage: "initial" | "repair" | "drop" | "skipped-drop";
  readonly selectionId: string;
  readonly outcome: "solved" | "placement-failed" | "circulation-blocked" | "unsupported" | "skipped";
  readonly changedRequestIds?: ReadonlyArray<string>;
  readonly droppedRequestIds?: ReadonlyArray<string>;
  readonly detail: string;
  readonly limitingConstraint?: LimitingConstraint | null;
  readonly attemptedCandidates: number;
}

export interface ArrangementHistory {
  readonly initialSelectionId: string;
  readonly attempts: ReadonlyArray<ArrangementAttempt>;
  readonly repairLimit?: 2;
  readonly optionalRequestLimit: number;
  readonly maxSolveAttempts: number;
  readonly maxCandidatesPerSolve: number;
  readonly totalAttemptedCandidates: number;
}

export interface ArrangementRequest {
  readonly room: RoomShell;
  readonly selections: ReadonlyArray<ArrangementSelection>;
  readonly policies: ReadonlyArray<PlacementPolicy>;
  readonly clearanceWidthM: number;
  readonly maxCandidates?: number;
}

export interface ArrangementSelection {
  readonly id: string;
  readonly intents: ReadonlyArray<PlacementIntent>;
}

export interface Attribution {
  readonly source: string;
  readonly holder: string;
  readonly license: string;
  readonly licenseUrl: string;
  readonly sourceUrl: string;
  readonly materialUrl: string;
  readonly citation: string;
  readonly modifications: string;
  readonly licenseStatus: "verified" | "unknown" | "conflicting-source-records";
  readonly licenseNote: string;
  readonly licenseEvidence: ReadonlyArray<LicenseEvidence>;
}

export interface CatalogueGallery {
  readonly catalogueVersion: string;
  readonly products: ReadonlyArray<Product>;
}

export interface CirculationClear {
  readonly status: "clear";
  readonly clearanceWidthM: number;
  readonly accessRegions: ReadonlyArray<CirculationRegion>;
  readonly gridResolutionM: number;
  readonly validatedNodes: number;
  readonly exhaustive: boolean;
}

export interface CirculationRegion {
  readonly id: string;
  readonly ownerType: "door" | "product";
  readonly ownerId: string;
  readonly corners: readonly [readonly [number, number], readonly [number, number], readonly [number, number], readonly [number, number]];
}

export interface DesignFailure {
  readonly status: "failed";
  readonly reason: "unsupported-intent" | "unknown-fixture-reference" | "unknown-product-reference" | "unknown-wall-reference" | "duplicate-intent-reference" | "unknown-intent-reference" | "self-intent-reference" | "cyclic-intent-reference" | "invalid-flanking-group" | "invalid-relative-gap" | "product-face-not-supported" | "nonadjacent-corner-walls" | "corner-angle-not-supported" | "product-exceeds-ceiling-height" | "intent-unsatisfiable" | "search-exhausted" | "product-collision" | "access-region-blocked" | "opening-exclusion" | "door-swing-exclusion" | "unknown-zone-reference" | "zone-derivation-unsupported" | "NO_VALID_DESIGN";
  readonly detail: string;
  readonly failedIntentId: string;
  readonly search: SearchReport;
  readonly zones?: ReadonlyArray<Zone>;
  readonly limitingConstraint?: LimitingConstraint | null;
  readonly arrangementHistory?: ArrangementHistory | null;
}

export interface DesignFixture {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly intentKind: "against" | "centred_on" | "in_corner" | "adjacent_to" | "facing" | "flanking" | "in_zone";
  readonly expectedOutcome: "solved" | "failed";
  readonly arrangement?: boolean;
}

export interface DesignFixtures {
  readonly fixtures: ReadonlyArray<DesignFixture>;
}

export interface DesignRequest {
  readonly room: RoomShell;
  readonly intents: ReadonlyArray<PlacementIntent>;
  readonly maxCandidates?: number;
}

export type DesignResult = SolvedDesign | DesignFailure;

export interface Dimensions {
  readonly widthM: number;
  readonly heightM: number;
  readonly depthM: number;
}

export interface DoorSwing {
  readonly hingeSide: "start" | "end";
}

export interface FitMeasurements {
  readonly footprint: Footprint;
  readonly clearanceM: number;
  readonly wallGapM: number | null;
  readonly heightM: number;
  readonly floorGapM: number;
  readonly topM: number;
}

export type FitResult = FitSuccess | InvalidFit;

export interface FitSuccess {
  readonly status: "fits";
  readonly placement: Placement;
  readonly measurements: FitMeasurements;
}

export interface FixtureSelectionRequest {
  readonly fixtureId: string;
  readonly maxCandidates?: number;
}

export interface Footprint {
  readonly centre: readonly [number, number];
  readonly yaw: number;
  readonly widthM: number;
  readonly depthM: number;
  readonly corners: readonly [readonly [number, number], readonly [number, number], readonly [number, number], readonly [number, number]];
}

export interface Health {
  readonly status: "ok";
}

export interface InvalidFit {
  readonly status: "invalid-fit";
  readonly reason: "product-exceeds-room-bounds" | "footprint-outside-room" | "access-region-outside-room" | "wall-contact-face-not-allowed" | "not-touching-declared-wall" | "wall-shorter-than-product" | "exceeds-ceiling-height" | "placement-class-cannot-stand-on-floor" | "not-resting-on-floor" | "wall-contact-not-aligned" | "product-collision" | "access-region-blocked" | "opening-exclusion" | "door-swing-exclusion";
  readonly detail: string;
  readonly productId: string;
  readonly roomId: string;
  readonly measurements: FitMeasurements;
}

export interface LicenseEvidence {
  readonly label: string;
  readonly recordedLicense: string;
  readonly url: string;
}

export interface LimitingConstraint {
  readonly code: string;
  readonly detail: string;
  readonly failedRequestId?: string;
  readonly disconnectedAccessIds?: ReadonlyArray<string>;
  readonly implicatedRequestIds?: ReadonlyArray<string>;
  readonly clearanceWidthM?: number | null;
  readonly attributionLimited?: boolean;
  readonly attributionLimitation?: string | null;
  readonly gridResolutionM?: number | null;
  readonly exhaustive: boolean;
}

export interface LiveBedroomConfig {
  readonly roomType?: "bedroom";
  readonly referenceSetVersion: string;
  readonly referenceApproval: "pending" | "approved";
  readonly scheduleApproval: "pending" | "approved";
  readonly references: ReadonlyArray<PublicReference>;
  readonly providerModel?: "claude-opus-5";
  readonly providerCapability?: "verified";
  readonly realCallsEnabled: boolean;
  readonly phoneGate?: "waived";
}

export interface LiveGenerationFailure {
  readonly status: "failed";
  readonly generationId: string;
  readonly referenceId: string;
  readonly code: "configuration-error" | "budget-error" | "transport-error" | "timeout" | "rate-limit" | "provider-error" | "provider-schema-error" | "selection-correction-exhausted" | "eligible-catalogue-error" | "no-valid-design";
  readonly detail: string;
  readonly providerModel?: string;
  readonly providerCalls: number;
  readonly modelLatencyMs: number;
  readonly usage: UsageSummary;
  readonly selectionRejections?: ReadonlyArray<SelectionRejection>;
  readonly designFailure?: DesignFailure | null;
}

export interface LiveGenerationRequest {
  readonly roomType: "bedroom";
  readonly referenceId: string;
}

export type LiveGenerationResult = LiveGenerationSuccess | LiveGenerationFailure;

export interface LiveGenerationSuccess {
  readonly status: "solved";
  readonly generationId: string;
  readonly referenceId: string;
  readonly providerModel: string;
  readonly providerCalls: number;
  readonly modelLatencyMs: number;
  readonly usage: UsageSummary;
  readonly selectionRejections?: ReadonlyArray<SelectionRejection>;
  readonly design: SolvedDesign;
}

export interface MeshBounds {
  readonly min: readonly [number, number, number];
  readonly max: readonly [number, number, number];
}

export interface MeshLod {
  readonly level: 0 | 1 | 2;
  readonly url: string;
  readonly triangles: number;
  readonly exclusiveBytes: number;
}

export interface MeshNormalization {
  readonly unit: "m";
  readonly upAxis: "+y";
  readonly frontAxis: "+z";
  readonly originRule: "floor-centre";
  readonly transform: MeshTransform;
  readonly note: string;
}

export interface MeshRef {
  readonly lods: ReadonlyArray<MeshLod>;
  readonly sharedTextureUrls: ReadonlyArray<string>;
  readonly normalization: MeshNormalization;
  readonly boundsM: MeshBounds;
  readonly totalCompressedBytes: number;
}

export interface MeshTransform {
  readonly translation: readonly [number, number, number];
  readonly rotationYaw: number;
  readonly scale: number;
}

export interface Opening {
  readonly id: string;
  readonly kind: "door" | "window";
  readonly wallId: string;
  readonly offsetAlongWallM: number;
  readonly widthM: number;
  readonly bottomM: number;
  readonly heightM: number;
  readonly clearanceDepthM: number;
  readonly doorSwing?: DoorSwing | null;
}

export interface Placement {
  readonly instanceId?: string | null;
  readonly productId: string;
  readonly position: readonly [number, number, number];
  readonly yaw: number;
  readonly wallContact?: WallContact | null;
  readonly wallContacts?: ReadonlyArray<WallContact>;
}

export interface PlacementIntent {
  readonly id: string;
  readonly kind: string;
  readonly productId: string;
  readonly wallId?: string | null;
  readonly face?: "front" | "back" | "left" | "right";
  readonly adjacentWallId?: string | null;
  readonly zoneId?: string | null;
  readonly referenceId?: string | null;
  readonly side?: "front" | "back" | "left" | "right" | null;
  readonly gapM?: number;
}

export interface PlacementPolicy {
  readonly requestId: string;
  readonly required: boolean;
  readonly anchor: boolean;
  readonly optionalKind?: "decoration" | "secondary-furniture" | null;
}

export interface PlacementValidationRequest {
  readonly product: Product;
  readonly room: RoomShell;
  readonly placement: Placement;
}

export interface PreviewDesign {
  readonly room: RoomShell;
  readonly product: Product;
  readonly fit: FitSuccess | InvalidFit;
}

export interface Product {
  readonly id: string;
  readonly displayName: string;
  readonly brand: string;
  readonly colour: string;
  readonly category: "bed" | "nightstand" | "wardrobe" | "dresser" | "chair" | "sofa" | "table" | "rug" | "lamp";
  readonly roomTypes: ReadonlyArray<"bedroom" | "living-room">;
  readonly dimensionsM: Dimensions;
  readonly frontAxis: "+z";
  readonly wallContactFaces: ReadonlyArray<"front" | "back" | "left" | "right">;
  readonly placementClass: "floor-standing" | "floor-covering" | "wall-mounted" | "ceiling-hung" | "surface-standing";
  readonly accessRegions: ReadonlyArray<AccessRegion>;
  readonly mesh: MeshRef;
  readonly purchaseUrl: string;
  readonly purchase: PurchaseDisclosure;
  readonly attribution: Attribution;
}

export interface PublicReference {
  readonly id: string;
  readonly label: string;
  readonly imageUrl: string;
  readonly creator: string;
  readonly sourceUrl: string;
  readonly license: string;
  readonly licenseUrl: string;
  readonly sha256: string;
}

export interface PurchaseDisclosure {
  readonly availability: "purchasable" | "unavailable" | "unknown";
  readonly checkedOn: string;
  readonly note: string;
}

export interface RoomShell {
  readonly id: string;
  readonly floorPolygon: ReadonlyArray<readonly [number, number]>;
  readonly walls: ReadonlyArray<WallSegment>;
  readonly ceilingHeightM: number;
  readonly openings?: ReadonlyArray<Opening>;
}

export interface SearchReport {
  readonly attemptedCandidates: number;
  readonly candidateLimit: number;
  readonly exhaustive: boolean;
}

export interface SelectionRejection {
  readonly code: "operation-shape-error" | "ineligible-product-error" | "selection-scope-error" | "anchor-error" | "wall-face-error" | "corner-face-error" | "graph-error" | "repair-identity-error" | "repair-anchor-error" | "repair-category-error";
  readonly detail: string;
  readonly path?: string | null;
  readonly intentId?: string | null;
}

export interface SolvedDesign {
  readonly status: "solved";
  readonly room: RoomShell;
  readonly intents: ReadonlyArray<PlacementIntent>;
  readonly products: ReadonlyArray<Product>;
  readonly placements: ReadonlyArray<Placement>;
  readonly fits: ReadonlyArray<FitSuccess>;
  readonly search: SearchReport;
  readonly zones?: ReadonlyArray<Zone>;
  readonly circulation?: CirculationClear | null;
  readonly arrangementHistory?: ArrangementHistory | null;
  readonly swap?: SwapSessionAvailable | SwapUnavailable | null;
}

export interface SwapAccepted {
  readonly status?: "accepted";
  readonly sessionId: string;
  readonly version: number;
  readonly detail: string;
  readonly design: SolvedDesign;
}

export interface SwapCandidate {
  readonly product: Product;
}

export type SwapCandidateResult = SwapCandidates | SwapNoCompatibleCandidates | SwapStaleVersion | SwapUnknownSession | SwapExpiredSession | SwapCatalogueChanged | SwapUnknownInstance;

export interface SwapCandidates {
  readonly status?: "candidates";
  readonly sessionId: string;
  readonly currentVersion: number;
  readonly instanceId: string;
  readonly candidates: ReadonlyArray<SwapCandidate>;
  readonly rejected: ReadonlyArray<SwapRejectedCandidate>;
  readonly detail: string;
}

export interface SwapCatalogueChanged {
  readonly status?: "catalogue-changed";
  readonly detail: string;
}

export interface SwapCurrent {
  readonly status?: "current";
  readonly sessionId: string;
  readonly version: number;
  readonly design: SolvedDesign;
}

export type SwapCurrentResult = SwapCurrent | SwapUnknownSession | SwapExpiredSession | SwapCatalogueChanged;

export interface SwapExpiredSession {
  readonly status?: "expired-session";
  readonly detail: string;
}

export type SwapMutationResult = SwapAccepted | SwapRejected | SwapStaleVersion | SwapUnknownSession | SwapExpiredSession | SwapCatalogueChanged | SwapUnknownInstance | SwapUnknownProduct | SwapNoOp | SwapNoCompatibleCandidates;

export interface SwapNoCompatibleCandidates {
  readonly status?: "no-compatible-candidates";
  readonly detail: string;
  readonly currentVersion: number;
  readonly instanceId: string;
  readonly rejected?: ReadonlyArray<SwapRejectedCandidate>;
}

export interface SwapNoOp {
  readonly status?: "no-op";
  readonly detail: string;
  readonly currentVersion: number;
}

export interface SwapRejected {
  readonly status?: "rejected";
  readonly code: string;
  readonly detail: string;
  readonly currentVersion: number;
}

export interface SwapRejectedCandidate {
  readonly product: Product;
  readonly code: string;
  readonly detail: string;
}

export interface SwapRequest {
  readonly sessionId: string;
  readonly expectedVersion: number;
  readonly instanceId: string;
  readonly replacementProductId: string;
}

export interface SwapSessionAvailable {
  readonly status?: "available";
  readonly sessionId: string;
  readonly version: number;
  readonly catalogueVersion: string;
  readonly clearanceWidthM: number;
}

export interface SwapStaleVersion {
  readonly status?: "stale-version";
  readonly detail: string;
  readonly currentVersion: number;
}

export interface SwapUnavailable {
  readonly status?: "unavailable";
  readonly detail: string;
}

export interface SwapUnknownInstance {
  readonly status?: "unknown-instance";
  readonly detail: string;
  readonly currentVersion: number;
}

export interface SwapUnknownProduct {
  readonly status?: "unknown-product";
  readonly detail: string;
  readonly currentVersion: number;
}

export interface SwapUnknownSession {
  readonly status?: "unknown-session";
  readonly detail: string;
}

export interface UsageSummary {
  readonly known: boolean;
  readonly inputTokens?: number | null;
  readonly outputTokens?: number | null;
  readonly costUsd?: number | null;
}

export interface WallContact {
  readonly wallId: string;
  readonly face: "front" | "back" | "left" | "right";
}

export interface WallSegment {
  readonly id: string;
  readonly label: string;
  readonly start: readonly [number, number];
  readonly end: readonly [number, number];
}

export interface Zone {
  readonly id: string;
  readonly label: string;
  readonly bounds: ZoneBounds;
  readonly coordinateOrder?: "minX,minZ,maxX,maxZ";
}

export interface ZoneBounds {
  readonly minX: number;
  readonly minZ: number;
  readonly maxX: number;
  readonly maxZ: number;
}

export interface ZoneDerivationFailure {
  readonly status: "ZONE_DERIVATION_UNSUPPORTED";
  readonly detail: string;
}

export interface ZoneDerivationReport {
  readonly method?: "axis-aligned-subdivide-merge-v1";
  readonly subdivisionM: number;
  readonly boundaryToleranceM: number;
  readonly minimumWidthM: number;
  readonly minimumDepthM: number;
  readonly maxIntervalsPerAxis: number;
  readonly maxAtomicCells: number;
}

export interface ZoneOffer {
  readonly status?: "offered";
  readonly roomId: string;
  readonly zones: ReadonlyArray<Zone>;
  readonly derivation: ZoneDerivationReport;
}

export interface ZoneRequest {
  readonly room: RoomShell;
}

export type ZoneResult = ZoneOffer | ZoneDerivationFailure;
